name: pbdl
description: Parabeac Design Layer
version: 1.0.0

environment:
  sdk: ">=3.0.0 <3.8.0"

dependencies:
  archive: ^3.3.2
  azblob: ^4.0.0
  get_it: ^7.6.4
  hex: ^0.2.0
  http2: ^2.2.1
  json_annotation: ^4.9.0
  meta: ^1.11.0
  path: ^1.9.0
  quick_log: ^5.5.3
  recase: ^4.1.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  pedantic: ^1.11.1
  test: ^1.25.2
